name: obida_app
description: A new Flutter project.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  

  cupertino_icons: ^1.0.2
 
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  firebase_database: ^10.2.2 
  fluttertoast: ^8.2.2
  image_cropper: ^5.0.0
  image_picker: ^0.8.8
  intl: ^0.18.0
  uuid: ^3.0.7
 
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

 
