// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRhL6gzycU_UH6lyDPI-m-5WiT7mt4Fpg',
    appId: '1:122896103170:web:663f965926e1a0bc8ff41b',
    messagingSenderId: '122896103170',
    projectId: 'productsharingproject-7f9da',
    authDomain: 'productsharingproject-7f9da.firebaseapp.com',
    databaseURL: 'https://productsharingproject-7f9da-default-rtdb.firebaseio.com',
    storageBucket: 'productsharingproject-7f9da.appspot.com',
    measurementId: 'G-37DZCRFRZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABipcYE1qzknfjqd6F63ftnWpa_HEA4t0',
    appId: '1:122896103170:android:c261914760a4128d8ff41b',
    messagingSenderId: '122896103170',
    projectId: 'productsharingproject-7f9da',
    databaseURL: 'https://productsharingproject-7f9da-default-rtdb.firebaseio.com',
    storageBucket: 'productsharingproject-7f9da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0W9SwDsJ4WuptLrLSk9lz6F7GzFafigM',
    appId: '1:122896103170:ios:9e09a46a8a93abef8ff41b',
    messagingSenderId: '122896103170',
    projectId: 'productsharingproject-7f9da',
    databaseURL: 'https://productsharingproject-7f9da-default-rtdb.firebaseio.com',
    storageBucket: 'productsharingproject-7f9da.appspot.com',
    iosClientId: '122896103170-0s2l121t36i0okamb97a854ko5a80bn6.apps.googleusercontent.com',
    iosBundleId: 'com.beyzacebiturk.sharingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0W9SwDsJ4WuptLrLSk9lz6F7GzFafigM',
    appId: '1:122896103170:ios:b9f5742fd12a60428ff41b',
    messagingSenderId: '122896103170',
    projectId: 'productsharingproject-7f9da',
    databaseURL: 'https://productsharingproject-7f9da-default-rtdb.firebaseio.com',
    storageBucket: 'productsharingproject-7f9da.appspot.com',
    iosClientId: '122896103170-qtu4jm8kg2vd1ej91qrvjpl1u7e4n4ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.obidaApp.RunnerTests',
  );
}
